services:
  data:
    container_name: type-ahead-data
    build:
      context: data
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/artifacts:/artifacts
  dev:
    container_name: type-ahead-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    command:
      - "target/debug/type_ahead"
    ports:
      - 5000:5000/tcp
    volumes:
      - ./src:/type_ahead/src
      - ./target:/type_ahead/target
  release:
    container_name: type-ahead-release
    build:
      context: .
      dockerfile: release.Dockerfile
    command:
      - "target/release/type_ahead"
    ports:
      - 5000:5000/tcp
  lambda:
    container_name: type-ahead-lambda
    build:
      context: .
      dockerfile: lambda.Dockerfile
    # TODO: just copy/pasting, i doubt these are right
    #command: /usr/local/cargo/bin/cargo lambda watch
    ports:
      - 9000:9000/tcp