services:
  data:
    container_name: typeahead-data
    build:
      context: data
      dockerfile: Dockerfile
  
  dev:
    container_name: typeahead-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    command:
      - "/app/target/debug/type_ahead"
    environment:
      TYPEAHEAD_PORT: "5000"
    ports:
      - 5000:5000/tcp
    volumes:
      - ./app:/app

  release:
    container_name: typeahead-release
    build:
      context: .
      dockerfile: release.Dockerfile
    command:
      - "/app/target/release/type_ahead"
    ports:
      - 5000:5000/tcp
  
  lambda:
    container_name: typeahead-lambda
    build:
      context: .
      dockerfile: lambda.Dockerfile
    # TODO: just copy/pasting, i doubt these are right
    command: "/usr/local/cargo/bin/cargo lambda watch"
    ports:
      - 9000:9000/tcp
  
  #dev2:
  #  container_name: typeahead-dev2
  #  build:
  #    context: .
  #    dockerfile: dev2.Dockerfile
  #  command:
  #    - "/app/target/debug/type_ahead"
  #  ports:
  #    - 5000:5000/tcp
  #  #volumes:
  #  #  - ./src:/app/src
  #  #  #- ./target:/app/target
  #debug:
  #  container_name: typeahead-debug
  #  build:
  #    context: .
  #    dockerfile: debug.Dockerfile