[package]
name = "type_ahead"
version = "0.1.0"
edition = "2021"

[dependencies]
type_ahead_db = { path = "../db" }

actix-web = "4"
r2d2 = "*"
r2d2_sqlite = "*"
rusqlite = "*"
serde = { version = "1", features = ["derive"]}